INSERT INTO country (code, name) VALUES ('NG', 'Nigeria');
INSERT INTO country (code, name) VALUES ('EG', 'Egypt');
INSERT INTO country (code, name) VALUES ('ZA', 'South Africa');
INSERT INTO country (code, name) VALUES ('KE', 'Kenya');
INSERT INTO country (code, name) VALUES ('CN', 'China');
INSERT INTO country (code, name) VALUES ('IN', 'India');
INSERT INTO country (code, name) VALUES ('JP', 'Japan');
INSERT INTO country (code, name) VALUES ('SA', 'Saudi Arabia');
INSERT INTO country (code, name) VALUES ('KR', 'South Korea');
INSERT INTO country (code, name) VALUES ('ID', 'Indonesia');
INSERT INTO country (code, name) VALUES ('DE', 'Germany');
INSERT INTO country (code, name) VALUES ('FR', 'France');
INSERT INTO country (code, name) VALUES ('GB', 'United Kingdom');
INSERT INTO country (code, name) VALUES ('IT', 'Italy');
INSERT INTO country (code, name) VALUES ('ES', 'Spain');
INSERT INTO country (code, name) VALUES ('PL', 'Poland');
INSERT INTO country (code, name) VALUES ('US', 'United States');
INSERT INTO country (code, name) VALUES ('CA', 'Canada');
INSERT INTO country (code, name) VALUES ('MX', 'Mexico');
INSERT INTO country (code, name) VALUES ('BR', 'Brazil');
INSERT INTO country (code, name) VALUES ('AR', 'Argentina');
INSERT INTO country (code, name) VALUES ('CO', 'Colombia');
INSERT INTO country (code, name) VALUES ('AU', 'Australia');
INSERT INTO country (code, name) VALUES ('NZ', 'New Zealand');
