spring:
  application:
    name: fullstack-application
  datasource:
    url: "jdbc:h2:file:./backend/src/main/resources/db/demo"
    #url: "jdbc:h2:./target/db;DB_CLOSE_ON_EXIT=FALSE;"
    #url: "jdbc:h2:file:~/testdb"
    #url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    #generate-ddl: true #why ?
    #properties:
    #  hibernate:
    #    show_sql: true
    #  ddl-auto: none #why ?
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
