server:
  port: 8080

spring:
  application:
    name: fullstack-application
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: "jdbc:h2:file:~/backend/src/main/resources/db/demo"
    #url: "jdbc:h2:./target/db;DB_CLOSE_ON_EXIT=FALSE;"
    #url: "jdbc:h2:file:~/testdb"
    #url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: create-drop
    defer-datasource-initialization: true
    #generate-ddl: true #why ?
    #properties:
    #  hibernate:
    #    show_sql: true
    #  ddl-auto: none #why ?
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: always